# http://module-build.sourceforge.net/META-spec.html
#
name:         Text-Phonetic-TransMetaphone
version:      1.0
version_from: TransMetaphone.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
